source:
  - changed-files:
      - any-glob-to-any-file: 'src/**/*'
action:
  - changed-files:
      - any-glob-to-any-file: 'action.yml'
tests:
  - changed-files:
      - any-glob-to-any-file:
          - '__tests__/**/*'
          - '__fixtures__/**/*'
gha:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
