name: 'Install azcopy'
description: 'Install azcopy and add it to PATH'
author: 'kheiakiyama'
inputs:
  version:
    description: 'azcopy version to download. (currently can set `v10` only)'
    default: 'v10'
  creds:
    description: 'Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS'
branding:
  icon: 'triangle'  
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/index.js'
